apiVersion: skiperator.kartverket.no/v1alpha1
kind: Application
metadata:
  name: database
spec:
  image: postgres
  port: 5432
  replicas: 1
  env:
    - name: POSTGRES_USER
      value: user
    - name: POSTGRES_PASSWORD
      value: pwd
    - name: POSTGRES_DB
      value: token-exchange
    - name: PGDATA
      value: /tmp/data
  appProtocol: tcp
  filesFrom:
    - emptyDir: postgresql
      mountPath: /var/run/postgresql
  accessPolicy:
    outbound:
      rules:
        - application: tokendings
    inbound:
      rules:
        - application: tokendings

