apiVersion: skiperator.kartverket.no/v1alpha1
kind: Application
metadata:
  name: fake-auth
  namespace: obo
spec:
  image: ghcr.io/bekk/obo-flyt/fake-auth:main
  port: 6348
  replicas: 1
  accessPolicy:
    outbound:
      rules:
        - application: tokendings
      external:
        - host: login.microsoftonline.com
    inbound:
      rules:
        - application: tokendings
