apiVersion: skiperator.kartverket.no/v1alpha1
kind: Application
metadata:
  name: some-app
  namespace: obo
spec:
  image: ghcr.io/bekk/obo-flyt/some-app:main
  port: 6349
  replicas: 1
  accessPolicy:
    outbound:
      rules:
        - application: tokendings
        - application: fake-auth
    inbound:
      rules:
        - application: tokendings
        # - application: test-app
        # - application: fake-auth
  env:
    - name: TOKEN_X_PRIVATE_JWK
      valueFrom:
        secretKeyRef:
          key: TOKEN_X_PRIVATE_JWK
          name: jwker-some-app
          optional: false
    - name: TOKEN_X_CLIENT_ID
      valueFrom:
        secretKeyRef:
          key: TOKEN_X_CLIENT_ID
          name: jwker-some-app
          optional: false
    - name: TOKEN_X_TOKEN_ENDPOINT
      valueFrom:
        secretKeyRef:
          key: TOKEN_X_TOKEN_ENDPOINT
          name: jwker-some-app
          optional: false

---
apiVersion: nais.io/v1
kind: Jwker
metadata:
  name: some-app
  namespace: obo
spec:
  accessPolicy:
    inbound:
      rules:
        - application: tokendings
        - application: fake-auth
    outbound:
      rules:
        - application: tokendings
        - application: fake-auth
        - application: test-app
  secretName: jwker-some-app
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: some-app
  name: some-app
  namespace: obo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: some-app
  name: some-app
  namespace: obo
rules:
  - apiGroups:
      - "*"
    resources:
      - secrets
    verbs:
      - get
      - watch
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: some-app
  name: some-app
  namespace: obo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: some-app
subjects:
  - kind: ServiceAccount
    name: some-app
    namespace: obo
