apiVersion: skiperator.kartverket.no/v1alpha1
kind: Application
metadata:
  name: some-app
  namespace: obo
spec:
  image: ghcr.io/bekk/obo-flyt/some-app:main
  port: 6349
  replicas: 1
  accessPolicy:
    outbound:
      rules:
        - application: tokendings
        - application: fake-auth
    inbound:
      rules:
        - application: tokendings
        # - application: test-app
        - application: fake-auth
---
apiVersion: nais.io/v1
kind: Jwker
metadata:
  name: jwker-some-app
  namespace: obo
spec:
  accessPolicy:
    inbound:
      rules:
        - application: tokendings
        - application: fake-auth
    outbound:
      rules:
        - application: tokendings
        - application: fake-auth
        # - application: test-app
  secretName: some-app
