apiVersion: skiperator.kartverket.no/v1alpha1
kind: Application
metadata:
  name: test-app
  namespace: obo
spec:
  image: ghcr.io/bekk/obo-flyt/some-app:main
  port: 6349
  replicas: 1
  accessPolicy:
    outbound:
      rules:
        - application: tokendings
        - application: fake-auth
    inbound:
      rules:
        - application: tokendings
        - application: some-app
        - application: fake-auth
  env:
    - name: FAKEAUTH_JWKS_URI
      value: http://fake-auth:6348/discovery/v2.0/keys
    - name: TOKEN_X_PRIVATE_JWK
      valueFrom:
        secretKeyRef:
          key: TOKEN_X_PRIVATE_JWK
          name: jwker-test-app
          optional: false
    - name: TOKEN_X_CLIENT_ID
      valueFrom:
        secretKeyRef:
          key: TOKEN_X_CLIENT_ID
          name: jwker-test-app
          optional: false
    - name: TOKEN_X_TOKEN_ENDPOINT
      valueFrom:
        secretKeyRef:
          key: TOKEN_X_TOKEN_ENDPOINT
          name: jwker-test-app
          optional: false
    - name: TOKEN_X_JWKS_URI
      valueFrom:
        secretKeyRef:
          key: TOKEN_X_JWKS_URI
          name: jwker-test-app
          optional: false

---
apiVersion: nais.io/v1
kind: Jwker
metadata:
  name: test-app
  namespace: obo
spec:
  accessPolicy:
    inbound:
      rules:
        - application: some-app
    outbound:
      rules:
        - application: tokendings
  secretName: jwker-test-app
