apiVersion: skiperator.kartverket.no/v1alpha1
kind: Application
metadata:
  name: test-app
  namespace: obo
spec:
  image: ghcr.io/bekk/obo-flyt/some-app:pr-11
  port: 6349
  replicas: 1
  accessPolicy:
    tokenX: true
    texas: true
    outbound:
      rules:
        - application: tokendings
        - application: fake-auth
    inbound:
      rules:
        - application: some-app
  env:
    - name: CLUSTER_NAME
      valueFrom:
        configMapKeyRef:
          name: cluster-info
          key: CLUSTER_NAME
          optional: false
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: FAKEAUTH_LOGIN_URL
      value: http://fake-auth:6348/fake_auth
    - name: FAKEAUTH_JWKS_URI
      value: http://fake-auth:6348/discovery/v2.0/keys
